version: '3.1'

services:

  laviciacion-bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    container_name: laviciacion-bot
    image: laviciacion-bot
    env_file: bot/.env
    volumes:
     - ./bot:/app
  
  laviciacion-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: laviciacion-api
    image: laviciacion-api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
